TARGET = XC-1A

APP_NAME = app_example_multicore_fir

XCC_FLAGS =-O3 -g

USED_MODULES = module_fir

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
