TARGET = XC-1A

APP_NAME = 

XCC_FLAGS =-O3 -g

USED_MODULES = module_fir

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.


# Use the main Makefile from module_xcommon
-include ../module_xcommon/build/Makefile.common
-include ../../xcommon/module_xcommon/build/Makefile.common

